lib: [
  "_build/install/default/lib/animlib/META" {"META"}
  "_build/install/default/lib/animlib/opam" {"opam"}
  "_build/install/default/lib/animlib/animlib.cmi"
  "_build/install/default/lib/animlib/animlib.cmx"
  "_build/install/default/lib/animlib/animlib.cmt"
  "_build/install/default/lib/animlib/animlib.ml"
  "_build/install/default/lib/animlib/animlib__.cmi"
  "_build/install/default/lib/animlib/animlib__.cmx"
  "_build/install/default/lib/animlib/animlib__.cmt"
  "_build/install/default/lib/animlib/animlib__.ml-gen"
  "_build/install/default/lib/animlib/animlib__Shm_server.cmi"
  "_build/install/default/lib/animlib/animlib__Shm_server.cmx"
  "_build/install/default/lib/animlib/animlib__Shm_server.cmt"
  "_build/install/default/lib/animlib/shm_server.ml"
  "_build/install/default/lib/animlib/animlib.cma"
  "_build/install/default/lib/animlib/animlib.cmxa"
  "_build/install/default/lib/animlib/animlib.a"
  "_build/install/default/lib/animlib/animlib.cmxs"
]
