let classes = "class"
let eval = "eval"
let padding = "padding"
let margin = "margin"
let border = "border"
let anchor = "anchor"
let expand = "expand"
let place = "place"
let grid = "grid"
let rotation = "rotation"
let scale = "scale"
let border_round = "border_round"
let border_color = "border_color"
let fill_color = "fill_color"
let align = "align"
let anchor = "anchor"

let coords="coords"
let width="width"
let height="height"
let color="color"

let stroke_width="stroke_width"
let markers="markers"
let font_name="font_name"
let font_size="font_size"

let bbox="bbox"
