let classes = "class"
let eval = "eval"
let padding = "padding"
let margin = "margin"
let border = "border"
let anchor = "anchor"
let expand = "expand"
let place = "place"
let grid = "grid"
let rotation = "rotation"
let scale = "scale"
let border_color = "border_color"
let fill_color = "fill_color"

let coords="coords"
let width="width"
let height="height"
let color="color"
let font_size="font_size"

let bbox="bbox"
